### ISSUE TITLE
Switch to generators

### ISSUE THREAD

**Issue by TimothyGu** [pugjs/pug-lexer#30]
Currently, the lexer returns an array containing all the tokens. For very large jade files, this means that the array has to contain ALL of the tokens, and therefore has to use a lot of RAM. For instance, it takes 112 megabytes of RAM to lex and parse a 756-kilobyte test file created by concatenating [mixin.attrs.jade](https://github.com/jadejs/jade/blob/master/test/cases/mixin.attrs.jade) (if we don't copy the tokens in `Lexer#getTokens` it still takes 100 megabytes), when measured using GNU time.

To reduce this memory usage, we could consider using ES2015 generator functions on platforms where these are supported. In my preliminary tests, the same file only takes 91 megabytes to lex and parse, while being only marginally slower (~2%).

What's your opinion on this? Do you think the gains are enough to warrant the additional complexity?

---

The diffs I used:

jade-lexer:

``` diff
diff --git a/index.js b/index.js
index 54badd7..d76bc91 100644
--- a/index.js
+++ b/index.js
@@ -3,6 +3,7 @@
 var assert = require('assert');
 var characterParser = require('character-parser');
 var error = require('jade-error');
+var GeneratorFunction = require('generator-function');

 module.exports = lex;
 module.exports.Lexer = Lexer;
@@ -10,6 +11,14 @@ function lex(str, filename) {
   var lexer = new Lexer(str, filename);
   return JSON.parse(JSON.stringify(lexer.getTokens()));
 }
+if (GeneratorFunction) {
+  module.exports.lexIterator = Function('Lexer',
+    'return function* (str, filename) {\n' +
+    '  var lexer = new Lexer(str, filename);\n' +
+    '  yield* lexer.getIterator();\n' +
+    '}'
+  )(Lexer);
+}

 /**
  * Initialize `Lexer` with the given `str`.
@@ -1088,5 +1097,18 @@ Lexer.prototype = {
       this.advance();
     }
     return this.tokens;
-  }
+  },
+
+  getIterator: (function () {
+    if (GeneratorFunction) {
+      return GeneratorFunction('',
+        'while (!this.ended) {\n' +
+        '  this.advance();\n' +
+        '  if (this.tokens.length === 1) yield this.tokens[0];\n' +
+        '  else yield* this.tokens[Symbol.iterator]();\n' +
+        '  this.tokens = [];\n' +
+        '}'
+      );
+    }
+  })()
 };
```

token-stream:

``` diff
--- lib/array.js        2015-10-11 10:38:15.384840871 -0700
+++ lib/iterator.js     2015-10-11 10:56:40.112840871 -0700
@@ -2,28 +2,41 @@

 module.exports = TokenStream;
 function TokenStream(tokens) {
-  if (!Array.isArray(tokens)) {
-    throw new TypeError('tokens must be passed to TokenStream as an array.');
+  if (!tokens || !tokens[Symbol.iterator]) {
+    throw new TypeError('tokens must be passed to TokenStream as an iterable.');
   }
-  this._tokens = tokens;
+  this._iterator = tokens[Symbol.iterator]();
+  this._tokens = [];
 }
 TokenStream.prototype.lookahead = function (index) {
   if (this._tokens.length <= index) {
-    throw new Error('Cannot read past the end of a stream');
+    var j = index + 1 - this._tokens.length;
+    while (j--) {
+      var res = this._iterator.next();
+      if (res.done) throw new Error('Cannot read past the end of a stream');
+      this._tokens.push(res.value);
+    }
   }
   return this._tokens[index];
 };
 TokenStream.prototype.peek = function () {
-  if (this._tokens.length === 0) {
-    throw new Error('Cannot read past the end of a stream');
+  if (this._tokens.length) {
+    return this._tokens[0];
+  } else {
+    var res = this._iterator.next();
+    if (res.done) throw new Error('Cannot read past the end of a stream');
+    this._tokens[0] = res.value;
+    return res.value;
   }
-  return this._tokens[0];
 };
 TokenStream.prototype.advance = function () {
-  if (this._tokens.length === 0) {
-    throw new Error('Cannot read past the end of a stream');
+  if (this._tokens.length) {
+    return this._tokens.shift();
+  } else {
+    var res = this._iterator.next();
+    if (res.done) throw new Error('Cannot read past the end of a stream');
+    return res.value;
   }
-  return this._tokens.shift();
 };
 TokenStream.prototype.defer = function (token) {
   this._tokens.unshift(token);
```

**Comment by jeromew** [comment]
just a thought, but it seems to me that the jade pipeline could also benefit from a real streaming implementation, without resorting to generators. This would probably lower the memory usage.

I see that modifying the current implementation with generators could be an additional burden for client side compilation (it would need transpilation of the compiler) so it would be necessary I guess to measure the impact on the size of the client side compiler with or without generators.

For people who compile all of their jade files server side before publishing their app, I think that they are already aware of the ressource consumption during the compilation phase. Do you think 91MB versus 112MB is that big of a difference in that scenario ?

It could be interesting to refine what is jade's most used scenario because optimizing "speed versus memory" is always dependent on specific requirements imho.

**Comment by TimothyGu** [comment]
> just a thought, but it seems to me that the jade pipeline could also benefit from a real streaming implementation, without resorting to generators.

In principle, I would agree, but my lack of experiences with streams (or at least non-IO streams) makes me want to fret.

> I see that modifying the current implementation with generators could be an additional burden for client side compilation (it would need transpilation of the compiler)

The older array-based pipeline is kept in my patches, and therefore works with even Node.js 0.10 (and with client-side JS engines not supporting generators).

Note that the token-stream patch is a diff of `iterator.js` against `array.js`. Which is `require`d is chosen at run-time through an `index.js`.

> Do you think 91MB versus 112MB is that big of a difference in that scenario ?

Probably not for most people, but at least for me who does all his development on a 512 MB DigitalOcean VPS through SSH, smaller resource consumption is much appreciated.

> It could be interesting to refine what is jade's most used scenario because optimizing "speed versus memory" is always dependent on specific requirements imho.

2% speed loss is basically negligible while a 9% (or 19%) memory saving is pretty significant. No one feels the effect of a 30-second compilation process becoming 31 seconds while one does feel the effect of the kernel terminating the process because of OOM (again, the possibility of that happening is fairly small but also fairly undesirable for people like me).

**Comment by ForbesLindesay** [comment]
I have a few concerns with this.  First of all, to answer @jeromew's point, streaming would not be remotely practical for anything other than the lexer, since streams are really bad at representing tree-like structures such as an AST. Libraries like UglfiyJS, babel, etc. are almost never streaming for this reason.  Even browserify, which is probably one of the largest proponents of streams actually buffers the entirety of the data at several points, so sees none of the memory benefits expected from streaming.

We could stream the lexer though, I'm just not sure we should.
1. There's no question about it, it does introduce additional complexity.
2. In absolute terms, this is a very small reduction in memory consumption (in comparison to the total memory footprint of a typical node.js appliaction).  Keep in mind that 756KB is not a typical size for a jade file.  In my experience, an application is much more likely to contain many small (2 or 3 KB) jade files, and once the jade template has been compiled, the tokens can be GCed.
3. This would sacrifice the simplicity of the lexer output.  You could no-longer effortlessly cache the output of the lexer.
4. There may be other ways to improve memory footprint more dramatically without sacrificing the complexity of the application.

## Alternative Optimisation Suggestion

We are currently keeping line numbers on all tokens.  This is important for debugging (as well as linters etc.) but it's totally unnecessary on indents, outdents and newlines.  These three tokens probably make up a significant percentage of all tokens generated.  If we removed the line number (and column) info from those tokens we could avoid generating a separate copy of the token for each time it appears in the array.  Instead we could define them as constants at the top:

``` diff
+ var cachedTokens = {
+   newline: {},
+   indent: {},
+   outdent: {},
+ };

...

  tok: function(type, val){
+   if ((type in cachedTokens) && (val === undefined)) return cachedTokens[type];
    return val === undefined ?
      {type: type, line: this.lineno} :
      {type: type, line: this.lineno, val: val};
  },
```

**Comment by ForbesLindesay** [comment]
I think this isn't worth actively pursuing at this time, so I'm closing this issue.  We should absolutely look for ways to be more memory-efficient in the future.
