### ISSUE TITLE
Plugin API

### ISSUE THREAD

**Issue by ForbesLindesay** [pugjs/pug-lexer#41]
Add an extra option, `plugins` which should be an array of plugin objects.  Plugins can define methods to "override" any of the methods of the lexer which normally return `true` or `false` to indicate whether they should fall through.  For example, if you wanted to implement the "id" token as a plugin you could use:

``` js
opts =  {
  plugins: [
    {
      advance: function (lexer) {
        var tok = lexer.scan(/^#([\w-]+)/, 'id');
        if (tok) {
          lexer.tokens.push(tok);
          lexer.incrementColumn(tok.val.length);
          return true;
        }
        if (/^#/.test(lexer.input)) {
          lexer.error('INVALID_ID', '"' + /.[^ \t\(\#\.\:]*/.exec(this.input.substr(1))[0] + '" is not a valid ID.');
        }
      }
    }
  ]
};
```

Plugins should be called in sequence until one of them returns `true`.  In this way plugins can be combined relatively safely.

**Comment by TimothyGu** [comment]
... and a plugin could be packaged as an npm module like:

``` js
module.exports = {
  advance: function (lexer) {
    var tok = lexer.scan(/^#([\w-]+)/, 'id');
    if (tok) {
      lexer.tokens.push(tok);
      lexer.incrementColumn(tok.val.length);
      return true;
    }
    if (/^#/.test(lexer.input)) {
      lexer.error('INVALID_ID', '"' + /.[^ \t\(\#\.\:]*/.exec(this.input.substr(1))[0] + '" is not a valid ID.');
    }
  }
};
```

``` js
opts =  {
  plugins: [
    require('./my-plugin')
  ]
};
```

Nice!

**Comment by TimothyGu** [comment]
Okay, so I have implemented a [prototype](https://github.com/jadejs/jade-lexer/compare/plugins) for this.

Your test case doesn't work out of the box though, because of two things:
- The reference to `this.input` (in my prototype I used the plugin itself as the `this` context)
- The carefully curated order in `advance` is disrupted, thus the INVALID_ID test errors on valid Jade expressions like `#{tagName}`

**Comment by TimothyGu** [comment]
Another option for the implementation is adding hooks to every lexing function, which can get messy when you can call the lexer function from a plugin, which can call the plugin function itself again.

On this note, this implementation currently does not allow calling the next plugin in line _and_ do further processing, since `lexer.callLexerFunction` will start from the beginning of the `plugins` array. Perhaps we should add a `nextMethod` argument to the plugin function signature, which will be the function next in the chain, bound to the next plugin?

**Comment by ForbesLindesay** [comment]
That implementation looks pretty good to me.
- the reference to `this.input` was an accident, it should have been `lexer.input`
- I think that (unlike built in lexing functions) plugins should be built to just ignore anything they don't understand.

The updated plugin example would therefore be:

``` js
opts =  {
  plugins: [
    {
      advance: function (lexer) {
        var tok = lexer.scan(/^#([\w-]+)/, 'id');
        if (tok) {
          lexer.tokens.push(tok);
          lexer.incrementColumn(tok.val.length);
          return true;
        }
      }
    }
  ]
};
```

I think the `callLexerFunction` approach looks good to me.  Plugins can defer to the rest of the chain (by just returning `undefined` and they can call the built in implementation manually.  These options should be sufficient for some pretty powerful plugins.

**Comment by ForbesLindesay** [comment]
I think it would also be good to allow plugins to somehow override the behaviour of `assertExpression`, in order to support plugin that extend the JavaScript syntax, but that should probably be a separate/subsequent pull request as we need to think carefully about how such plugins would combine.

Do you feel like creating a pull request for your current plugin API?
