### ISSUE TITLE
Class name rules are too strict

### ISSUE THREAD

**Issue by rbardini** [pugjs/pug-lexer#60]
From HTML 4.01 onwards, the `class` attribute is [allowed to have weird values](https://mathiasbynens.be/demo/crazy-class), including Unicode symbols. The following code is perfectly valid:

``` html
<p class="#">Foo.
<p class="##">Bar.
<p class="♥">Baz.
<p class="©">Inga.
<p class="{}">Lorem.
<p class="“‘’”">Ipsum.
<p class="⌘⌥">Dolor.
<p class="{}">Sit.
<p class="[attr=value]">Amet.
```

However, the pug lexer [restricts class names](https://github.com/pugjs/pug-lexer/blob/852b3a4/index.js#L393-L409) to values begining with `-`,  `_` or a letter and only containing `_`, `-`, `a-z` and `0-9`. Is there a reason for it not being more loose?

**Comment by TimothyGu** [comment]
First, it is perhaps better to look at the rules for CSS which are a bit more applicable for us. 

> The **_class selector**_ is given as a full stop (`.` U+002E) immediately followed by an identifier.
> – [Selectors Level 4](https://www.w3.org/TR/selectors4/#class-html)
> 
> ![image](https://cloud.githubusercontent.com/assets/1538624/14944047/97743764-0f9d-11e6-9e6b-a35eefb5285c.png)
> – [CSS Syntax Module Level 3](https://www.w3.org/TR/css-syntax-3/#ident-token-diagram)

From the railway diagram above, it is pretty obvious that it is similar to what [we have](http://tinyurl.com/h9bee4o), except CSS has support for non-ASCII characters (edit: and escaping, which is too complicated for us since we have an alternative way of specifying class attribute anyway). This alone disqualifies several of your examples.

Now, the rationale for not adding support for Unicode has been detailed in https://github.com/pugjs/pug/issues/1796#issuecomment-68077675 and https://github.com/pugjs/pug/issues/1904#issuecomment-114142406. Tl;dr, we believe that it's more bullet-proof if we force our users to use the explicit string way (i.e. `(class='ʍəįɹp')`).
